# Generated by Django 5.1.3 on 2024-11-19 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ownerid', models.CharField(max_length=255)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('googleclassroomid', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
