# Generated by Django 5.1.3 on 2024-11-26 10:35

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ownerid', models.CharField(max_length=255)),
                ('alias', models.CharField(default='p', max_length=100)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('startdate', models.DateField(default=datetime.date.today)),
                ('googleclassroomid', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='djangoGoogleClassroom.course')),
                ('imagepath', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
            ],
        ),
    ]
