# Generated by Django 5.1.3 on 2024-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGoogleClassroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alias',
            field=models.CharField(default='p', max_length=100),
        ),
    ]
