# Generated by Django 5.1.3 on 2024-11-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGoogleClassroom', '0002_course_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='startdate',
            field=models.DateField(default=2023),
            preserve_default=False,
        ),
    ]
