# Generated by Django 5.1.3 on 2024-11-20 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGoogleClassroom', '0003_course_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='startdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
